version: '2.4'

services:
  db:
    image: postgres:11.11
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: zipi
      POSTGRES_PASSWORD: zipi
      POSTGRES_DB: zipi
      POSTGRES_PORT: 5432
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zipi"]
      interval: 10s
      timeout: 5s
      retries: 5
